name: gen_efi_app_python2_build
on:
  push:
    branches: [ main ]
    paths:
      - 'gen_efi_app/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'gen_efi_app/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gen_efi_app python2 package set up python
      uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - name: gen_efi_app python2 package install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt
    - name: gen_efi_app python2 package build
      run: |
        python setup.py --github sdist bdist_wheel
